# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_submodules

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('reader/templates', 'reader/templates'),
        ('reader/static', 'reader/static'),
        ('config.ini.example', '.'),
        ('alembic.ini', '.'),
        ('migrations', 'migrations'),
    ],
    hiddenimports=collect_submodules('py7zr') + [
        'jinja2',
        'reader',
        'reader.routes',
        'reader.routes.auth',
        'reader.routes.browse',
        'reader.routes.api_comic',
        'reader.routes.api_folder',
        'reader.routes.api_library',
        'reader.routes._common',
        'reader.services',
        'reader.repo',
        'reader.repo.folders',
        'reader.repo.comics',
        'reader.repo.metadata',
        'reader.repo.progress',
        'reader.repo.tags',
        'reader.repo.ongoing',
        'reader.auth',
        'server',
        'server.config',
        'server.database',
        'server.logging_config',
        'server.opds',
        'server.opds.middleware',
        'server.opds.feeds',
        'server.opds.routes',
        'server.archive',
        'server.comicinfo',
        'server.path_utils',
        'server.repository',
        'server.scanner',
        'server.thumbnails',
        'server.monitor',
        'server.models',
        'server.utils',
        'server.migrations',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'typer',
        'watchdog',
        'watchdog.observers',
        'watchdog.observers.polling',
        'PIL',
        'PIL._imaging',
        'rarfile',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'setuptools',
        'pip',
        'wheel',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='issued',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
